#!/bin/bash

################################################################################
# generic local build script for epics-containers ioc repositories             #
################################################################################

# set TARGET_ARCHITECTURE to rtems for RTEMS based targets
T_A=${TARGET_ARCHITECTURE:-linux}
# set TARGET to runtime for runtime images
TARGET=${TARGET:-developer}
# set TAG to override the default tag
TAG=${TAG:-ec_test}

# log commands and stop on erros
set -xe

cd $(dirname ${0})

# use docker if available else use podman, also use buildx if available
if ! docker version &>/dev/null; then docker=podman; else docker=docker; fi
if $docker buildx version &>/dev/null; then builx=buildx; load=--load; fi

# make sure new repos get their submodule ibek-support
# allow failure so that we can rebuild with dirty submodules
git submodule update --init || true

$docker $buildx build -t ${TAG} $load \
    --build-arg TARGET_ARCHITECTURE=$T_A \
    --target $TARGET .

