#!/bin/bash

################################################################################
# generic local build script for epics-containers repositories                 #
################################################################################

set -e

# set TARGET_ARCHITECTURE to rtems for RTEMS based targets
T_A=${TARGET_ARCHITECTURE:-linux_x86_64}
# set TARGET to runtime for runtime images
TARGET=${TARGET:-developer}
# set TAG to override the default tag
TAG=${TAG:-ec_test}

if [[ ${T_A} != "linux_x86_64" ]]; then
    # container image extension is the lcase of TARGET_ARCHITECTURE
    IMAGE_EXT=-"${T_A,,}"
    if [ "$T_A" = "RTEMS-beatnik" ]; then
        runtime="--build-arg RUNTIME=ghcr.io/epics-containers/rtems-proxy"
    fi
fi

cd $(dirname ${0})

# use docker if available else use podman
if ! docker version &>/dev/null; then docker=podman; else docker=docker; fi
if $docker buildx version &>/dev/null; then builx=buildx; load=--load; fi

# make sure new repos get their submodule ibek-support
if [ ! -d ibek-support ] ; then git submodule update --init ; fi

# build and developer images
set -x
$docker build $buildx -t ${TAG} "${@}" $load \
    --build-arg TARGET_ARCHITECTURE=$T_A \
    --build-arg IMAGE_EXT=$IMAGE_EXT \
    $runtime --target $TARGET .
